import PostsMeta from '@/components/getPosts'
import Link from 'next/link'

export const metadata = {
    title: 'Static Blog | Blog Home',
    description: 'This site was generated by Qube 6 Digital',
 }

const Posts = () => {
    const blogs = PostsMeta()

    return (
        <div className="posts mx-auto flex flex-col max-w-7xl">

            <div className='py-4'>
            {blogs.map((post) => (
                <div key={post.slug}>
                    <Link href={`post/${post.slug}`} className='hover:text-blue-400'><h2 className='text-2xl'>{post.title}</h2></Link>
                    <p className='text-sm'>{post.date}</p>
                </div>
            ))}
            </div>
        </div>
    )
}

export default Posts