import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: {
    default: 'Static Blog',
    template: '%s | Static Blog',
  },
  description: {
    default: 'Generated by The J-Man',
    template: '%s',
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <Navbar/>
        <main className='pt-[112px]'>
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  )
}
